# Generated by Django 2.1 on 2018-08-23 23:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_name', models.CharField(max_length=100)),
                ('preferred_name', models.CharField(blank=True, max_length=100, null=True)),
                ('surname', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], max_length=1)),
                ('sfu_id', models.IntegerField(blank=True, null=True)),
                ('birth_date', models.DateField()),
                ('address', models.CharField(max_length=200)),
                ('years_of_education', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('contact_pref', models.CharField(choices=[('P', 'Phone'), ('E', 'Email')], max_length=1)),
                ('pref_phone_time', models.CharField(blank=True, choices=[('WDM', 'Weekday Mornings'), ('WDA', 'Weekday Afternoons'), ('WDE', 'Weekday Evenings'), ('WEM', 'Weekend Mornings'), ('WEA', 'Weekend Afternoons'), ('WEE', 'Weekend Evenings'), ('DNC', 'Do Not Call'), ('ANY', 'Anytime')], max_length=3, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_name', models.CharField(max_length=100)),
                ('preferred_name', models.CharField(blank=True, max_length=100, null=True)),
                ('surname', models.CharField(default='', max_length=100)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], max_length=1)),
                ('gestation_length_weeks', models.SmallIntegerField(blank=True, null=True)),
                ('was_full_term', models.BooleanField(blank=True, null=True)),
                ('birth_weight', models.SmallIntegerField()),
                ('birth_height', models.SmallIntegerField()),
                ('personal_notes', models.TextField(max_length=1000)),
                ('hx_repeated_ear_infection', models.TextField(blank=True, max_length=1000, null=True)),
                ('last_ear_infection', models.DateField(blank=True, null=True)),
                ('hereditary_audio_problems', models.BooleanField()),
                ('hereditary_language_pathologies', models.BooleanField()),
                ('health_notes', models.TextField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Children',
            },
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment_name', models.CharField(max_length=100)),
                ('lab', models.CharField(choices=[('ld', 'LangDev'), ('ph', 'Phono')], max_length=2)),
                ('status', models.CharField(choices=[('prep', 'In Prep'), ('recruiting', 'Actively Recruiting'), ('inactive', 'Inactive')], max_length=10)),
            ],
            options={
                'verbose_name': 'Experiment',
                'verbose_name_plural': 'Experiments',
            },
        ),
        migrations.CreateModel(
            name='Experiment_Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment_section_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('prep', 'In Prep'), ('recruiting', 'Actively Recruiting'), ('inactive', 'Inactive')], max_length=10)),
                ('section_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParticipantDB.Experiment')),
            ],
            options={
                'verbose_name': 'Experiment Section',
                'verbose_name_plural': 'Experiment Sections',
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Families',
            },
        ),
        migrations.CreateModel(
            name='IsExposedTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage_exposure', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('child', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ParticipantDB.Child')),
            ],
            options={
                'verbose_name_plural': 'Is Exposed To',
            },
        ),
        migrations.CreateModel(
            name='IsParentIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary_contact', models.BooleanField()),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParticipantDB.Family')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParticipantDB.Adult')),
            ],
            options={
                'verbose_name_plural': 'Parents',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('language_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Musical_Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nth_most_dominant', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('age_learning_started', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('age_learning_ended', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
            ],
            options={
                'verbose_name': 'Musical Experience',
                'verbose_name_plural': 'Musical Experiences',
            },
        ),
        migrations.CreateModel(
            name='Musical_Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Musical Skill',
                'verbose_name_plural': 'Musical Skills',
            },
        ),
        migrations.CreateModel(
            name='Participated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notes', models.TextField(max_length=1000)),
                ('assessor', models.TextField(max_length=100)),
                ('adult_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParticipantDB.Adult')),
                ('child_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParticipantDB.Child')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParticipantDB.Experiment_Section')),
            ],
            options={
                'verbose_name': 'Participation',
                'verbose_name_plural': 'Participations',
            },
        ),
        migrations.CreateModel(
            name='Speaks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_native', models.BooleanField()),
                ('nth_most_dominant', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('age_learning_started', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('age_learning_ended', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('language', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ParticipantDB.Language')),
                ('person', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ParticipantDB.Adult')),
            ],
            options={
                'verbose_name_plural': 'Speaks',
            },
        ),
        migrations.AddField(
            model_name='musical_experience',
            name='experience',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ParticipantDB.Musical_Skill'),
        ),
        migrations.AddField(
            model_name='musical_experience',
            name='person',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ParticipantDB.Adult'),
        ),
        migrations.AddField(
            model_name='isexposedto',
            name='language',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ParticipantDB.Language'),
        ),
        migrations.AddField(
            model_name='child',
            name='exposed_to',
            field=models.ManyToManyField(default=None, through='ParticipantDB.IsExposedTo', to='ParticipantDB.Language'),
        ),
        migrations.AddField(
            model_name='child',
            name='family',
            field=models.ManyToManyField(to='ParticipantDB.Family'),
        ),
        migrations.AddField(
            model_name='child',
            name='participations',
            field=models.ManyToManyField(default=None, through='ParticipantDB.Participated', to='ParticipantDB.Experiment_Section'),
        ),
        migrations.AddField(
            model_name='adult',
            name='languages',
            field=models.ManyToManyField(through='ParticipantDB.Speaks', to='ParticipantDB.Language'),
        ),
        migrations.AddField(
            model_name='adult',
            name='musical_background',
            field=models.ManyToManyField(blank=True, through='ParticipantDB.Musical_Experience', to='ParticipantDB.Musical_Skill'),
        ),
        migrations.AddField(
            model_name='adult',
            name='parent_in',
            field=models.ManyToManyField(blank=True, through='ParticipantDB.IsParentIn', to='ParticipantDB.Family'),
        ),
        migrations.AddField(
            model_name='adult',
            name='participations',
            field=models.ManyToManyField(blank=True, through='ParticipantDB.Participated', to='ParticipantDB.Experiment_Section'),
        ),
    ]
