# Generated by Django 2.1 on 2018-11-22 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParticipantDB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment_section_run',
            name='notes',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
