# Generated by Django 2.1 on 2018-08-23 23:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParticipantDB', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experiment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='family',
            options={'verbose_name': 'Family', 'verbose_name_plural': 'Families'},
        ),
        migrations.RenameField(
            model_name='adult',
            old_name='participations',
            new_name='participation',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='id',
        ),
        migrations.RemoveField(
            model_name='musical_skill',
            name='id',
        ),
        migrations.AlterField(
            model_name='adult',
            name='pref_phone_time',
            field=models.CharField(blank=True, choices=[('WDM', 'Weekday Mornings'), ('WDA', 'Weekday Afternoons'), ('WDE', 'Weekday Evenings'), ('WEM', 'Weekend Mornings'), ('WEA', 'Weekend Afternoons'), ('WEE', 'Weekend Evenings'), ('ANY', 'Anytime')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='adult',
            name='years_of_education',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='experiment_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='isparentin',
            name='is_primary_contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='musical_skill',
            name='skill',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
