# Generated by Django 2.1 on 2018-12-19 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParticipantDB', '0002_auto_20181122_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='last_ear_infection',
        ),
    ]
