# Generated by Django 2.1 on 2018-08-23 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ParticipantDB', '0002_auto_20180823_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsChildIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary_contact', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Is Child In',
                'verbose_name_plural': 'Are Children In',
            },
        ),
        migrations.AlterModelOptions(
            name='isparentin',
            options={'verbose_name': 'Is Parent In', 'verbose_name_plural': 'Are Parents In'},
        ),
        migrations.RenameField(
            model_name='isparentin',
            old_name='person',
            new_name='parent',
        ),
        migrations.RemoveField(
            model_name='adult',
            name='parent_in',
        ),
        migrations.RemoveField(
            model_name='child',
            name='family',
        ),
        migrations.AddField(
            model_name='family',
            name='parents',
            field=models.ManyToManyField(through='ParticipantDB.IsParentIn', to='ParticipantDB.Adult'),
        ),
        migrations.AddField(
            model_name='ischildin',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParticipantDB.Child'),
        ),
        migrations.AddField(
            model_name='ischildin',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParticipantDB.Family'),
        ),
        migrations.AddField(
            model_name='family',
            name='children',
            field=models.ManyToManyField(through='ParticipantDB.IsChildIn', to='ParticipantDB.Child'),
        ),
    ]
