# Generated by Django 2.1 on 2019-01-01 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParticipantDB', '0003_auto_20190101_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaks',
            name='is_native',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
    ]
