# Generated by Django 2.1 on 2018-09-20 20:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ParticipantDB', '0003_auto_20180920_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicalExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nth_most_dominant', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('age_learning_started', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('age_learning_ended', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
            ],
            options={
                'verbose_name_plural': 'Musical Experiences',
            },
        ),
        migrations.CreateModel(
            name='MusicalSkill',
            fields=[
                ('skill', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Musical Skill',
                'verbose_name_plural': 'Musical Skills',
            },
        ),
        migrations.AddField(
            model_name='musicalexperience',
            name='experience',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='instrument', to='ParticipantDB.MusicalSkill'),
        ),
        migrations.AddField(
            model_name='musicalexperience',
            name='person',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='musician', to='ParticipantDB.Adult'),
        ),
        migrations.AddField(
            model_name='adult',
            name='musical_background',
            field=models.ManyToManyField(blank=True, through='ParticipantDB.MusicalExperience', to='ParticipantDB.MusicalSkill'),
        ),
    ]
