# Generated by Django 2.1 on 2018-12-19 18:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParticipantDB', '0003_remove_child_last_ear_infection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adult',
            name='years_of_education',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Years of Education'),
        ),
    ]
