# Generated by Django 2.1 on 2018-08-24 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParticipantDB', '0003_auto_20180823_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='adult',
            name='other_gender',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Other Gender'),
        ),
        migrations.AddField(
            model_name='child',
            name='other_gender',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Other Gender'),
        ),
        migrations.AlterField(
            model_name='adult',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other (Specify Below)')], max_length=1),
        ),
        migrations.AlterField(
            model_name='child',
            name='birth_height',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Birth Height (CM)'),
        ),
        migrations.AlterField(
            model_name='child',
            name='birth_weight',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Birth Weight (Grams)'),
        ),
        migrations.AlterField(
            model_name='child',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other (Specify Below)')], max_length=1),
        ),
        migrations.AlterField(
            model_name='child',
            name='personal_notes',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
