# Generated by Django 2.1 on 2018-09-20 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParticipantDB', '0004_auto_20180920_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='isexposedto',
            old_name='language',
            new_name='lang',
        ),
        migrations.RenameField(
            model_name='speaks',
            old_name='language',
            new_name='lang',
        ),
    ]
