# Generated by Django 2.1 on 2019-01-15 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ParticipantDB', '0004_auto_20190101_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='notes',
            field=models.TextField(blank=True, default=True, max_length=1000, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='assessment_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Assessment Name'),
        ),
        migrations.AlterField(
            model_name='assessment_run',
            name='participantAdult',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ParticipantDB.Adult', verbose_name='Adult Participant'),
        ),
        migrations.AlterField(
            model_name='assessment_run',
            name='participantChild',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ParticipantDB.Child', verbose_name='Child Participant'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='experiment_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Experiment Name'),
        ),
        migrations.AlterField(
            model_name='experiment_section_run',
            name='participantAdult',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ParticipantDB.Adult', verbose_name='Adult Participant'),
        ),
        migrations.AlterField(
            model_name='experiment_section_run',
            name='participantChild',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ParticipantDB.Child', verbose_name='Child Participant'),
        ),
        migrations.AlterField(
            model_name='language',
            name='language_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Language Name'),
        ),
        migrations.AlterField(
            model_name='musicalskill',
            name='skill',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Skill'),
        ),
    ]
