# Generated by Django 2.1 on 2018-08-31 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ParticipantDB', '0004_auto_20180823_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('assessment_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('flex_1_name', models.CharField(blank=True, max_length=100, null=True)),
                ('flex_1_min_value', models.SmallIntegerField(blank=True, null=True)),
                ('flex_1_max_value', models.SmallIntegerField(blank=True, null=True)),
                ('flex_2_name', models.CharField(blank=True, max_length=100, null=True)),
                ('flex_2_min_value', models.SmallIntegerField(blank=True, null=True)),
                ('flex_2_max_value', models.SmallIntegerField(blank=True, null=True)),
                ('flex_3_name', models.CharField(blank=True, max_length=100, null=True)),
                ('flex_3_min_value', models.SmallIntegerField(blank=True, null=True)),
                ('flex_3_max_value', models.SmallIntegerField(blank=True, null=True)),
                ('flex_4_name', models.CharField(blank=True, max_length=100, null=True)),
                ('flex_4_min_value', models.SmallIntegerField(blank=True, null=True)),
                ('flex_4_max_value', models.SmallIntegerField(blank=True, null=True)),
                ('flex_5_name', models.CharField(blank=True, max_length=100, null=True)),
                ('flex_5_min_value', models.SmallIntegerField(blank=True, null=True)),
                ('flex_5_max_value', models.SmallIntegerField(blank=True, null=True)),
                ('flex_6_name', models.CharField(blank=True, max_length=100, null=True)),
                ('flex_6_min_value', models.SmallIntegerField(blank=True, null=True)),
                ('flex_6_max_value', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assessment_Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notes', models.TextField(max_length=1000)),
                ('assessor', models.TextField(max_length=100)),
                ('flex_1_score', models.SmallIntegerField(blank=True, null=True)),
                ('flex_2_score', models.SmallIntegerField(blank=True, null=True)),
                ('flex_3_score', models.SmallIntegerField(blank=True, null=True)),
                ('flex_4_score', models.SmallIntegerField(blank=True, null=True)),
                ('flex_5_score', models.SmallIntegerField(blank=True, null=True)),
                ('flex_6_score', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Assessment Run',
                'verbose_name_plural': 'Assessment Runs',
            },
        ),
        migrations.CreateModel(
            name='Experiment_Section_Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notes', models.TextField(max_length=1000)),
                ('assessor', models.TextField(max_length=100)),
                ('flex_1_score', models.SmallIntegerField(blank=True, null=True)),
                ('flex_2_score', models.SmallIntegerField(blank=True, null=True)),
                ('flex_3_score', models.SmallIntegerField(blank=True, null=True)),
                ('flex_4_score', models.SmallIntegerField(blank=True, null=True)),
                ('flex_5_score', models.SmallIntegerField(blank=True, null=True)),
                ('flex_6_score', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Experiment Section Run',
                'verbose_name_plural': 'Experiment Section Runs',
            },
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('lab_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='participated',
            name='adult_participant',
        ),
        migrations.RemoveField(
            model_name='participated',
            name='child_participant',
        ),
        migrations.RemoveField(
            model_name='participated',
            name='section',
        ),
        migrations.RemoveField(
            model_name='adult',
            name='other_gender',
        ),
        migrations.RemoveField(
            model_name='adult',
            name='participation',
        ),
        migrations.RemoveField(
            model_name='child',
            name='other_gender',
        ),
        migrations.RemoveField(
            model_name='child',
            name='participations',
        ),
        migrations.RemoveField(
            model_name='ischildin',
            name='is_primary_contact',
        ),
        migrations.RemoveField(
            model_name='isparentin',
            name='is_primary_contact',
        ),
        migrations.AddField(
            model_name='adult',
            name='health_notes',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='experiment_section',
            name='flex_1_max_value',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiment_section',
            name='flex_1_min_value',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiment_section',
            name='flex_1_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experiment_section',
            name='flex_2_max_value',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiment_section',
            name='flex_2_min_value',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiment_section',
            name='flex_2_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experiment_section',
            name='flex_3_max_value',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiment_section',
            name='flex_3_min_value',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiment_section',
            name='flex_3_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experiment_section',
            name='flex_4_max_value',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiment_section',
            name='flex_4_min_value',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiment_section',
            name='flex_4_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experiment_section',
            name='flex_5_max_value',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiment_section',
            name='flex_5_min_value',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiment_section',
            name='flex_5_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experiment_section',
            name='flex_6_max_value',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiment_section',
            name='flex_6_min_value',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiment_section',
            name='flex_6_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='adult',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='adult',
            name='gender',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='adult',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='adult',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adult',
            name='pref_phone_time',
            field=models.CharField(choices=[('WDM', 'Weekday Mornings'), ('WDA', 'Weekday Afternoons'), ('WDE', 'Weekday Evenings'), ('WEM', 'Weekend Mornings'), ('WEA', 'Weekend Afternoons'), ('WEE', 'Weekend Evenings'), ('ANY', 'Anytime'), ('DNC', 'Do Not Call')], default='DNC', max_length=3),
        ),
        migrations.AlterField(
            model_name='child',
            name='gender',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='child',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParticipantDB.Lab'),
        ),
        migrations.DeleteModel(
            name='Participated',
        ),
        migrations.AddField(
            model_name='experiment_section_run',
            name='adult_participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParticipantDB.Adult'),
        ),
        migrations.AddField(
            model_name='experiment_section_run',
            name='child_participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParticipantDB.Child'),
        ),
        migrations.AddField(
            model_name='experiment_section_run',
            name='experiment_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParticipantDB.Experiment_Section'),
        ),
        migrations.AddField(
            model_name='assessment_run',
            name='adult_participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParticipantDB.Adult'),
        ),
        migrations.AddField(
            model_name='assessment_run',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParticipantDB.Assessment'),
        ),
        migrations.AddField(
            model_name='assessment_run',
            name='child_participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParticipantDB.Child'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParticipantDB.Lab'),
        ),
    ]
