# Generated by Django 2.1 on 2018-09-22 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParticipantDB', '0005_auto_20180920_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaks',
            name='is_native',
            field=models.BooleanField(default=False),
        ),
    ]
