# Generated by Django 2.1 on 2019-01-15 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParticipantDB', '0005_auto_20190114_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='notes',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Notes'),
        ),
    ]
