# Generated by Django 2.1 on 2018-12-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParticipantDB', '0005_auto_20181219_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='adult',
            name='personal_notes',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Personal Notes'),
        ),
    ]
