# Generated by Django 2.1 on 2018-09-05 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParticipantDB', '0005_auto_20180831_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adult',
            name='languages',
            field=models.ManyToManyField(related_name='languagesspoken', through='ParticipantDB.Speaks', to='ParticipantDB.Language'),
        ),
    ]
