# Generated by Django 2.1 on 2019-01-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParticipantDB', '0006_auto_20190114_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='isparentin',
            name='isPrimary',
            field=models.BooleanField(blank=True, null=True, verbose_name='Primary Contact?'),
        ),
    ]
