# Generated by Django 2.1 on 2018-09-05 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParticipantDB', '0006_auto_20180905_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adult',
            name='languages',
            field=models.ManyToManyField(through='ParticipantDB.Speaks', to='ParticipantDB.Language'),
        ),
    ]
