# Generated by Django 2.1 on 2018-09-05 23:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParticipantDB', '0007_auto_20180905_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musical_experience',
            name='age_learning_ended',
            field=models.SmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='musical_experience',
            name='age_learning_started',
            field=models.SmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)]),
            preserve_default=False,
        ),
    ]
