# Generated by Django 2.1 on 2018-12-29 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParticipantDB', '0007_auto_20181223_1538'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['language_name'], 'verbose_name': 'Language', 'verbose_name_plural': 'Languages'},
        ),
        migrations.RemoveField(
            model_name='experiment_section_run',
            name='assessor',
        ),
    ]
