# Generated by Django 2.1 on 2019-01-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParticipantDB', '0007_isparentin_isprimary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isparentin',
            name='isPrimary',
            field=models.BooleanField(default=False, null=True, verbose_name='Primary Contact?'),
        ),
    ]
