# Generated by Django 2.1 on 2018-09-05 23:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParticipantDB', '0008_auto_20180905_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musical_experience',
            name='nth_most_dominant',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
            preserve_default=False,
        ),
    ]
