# Generated by Django 2.1 on 2018-12-29 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParticipantDB', '0009_auto_20181228_1613'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adult',
            options={'ordering': ['id'], 'verbose_name': 'Adult', 'verbose_name_plural': 'Adults'},
        ),
        migrations.AlterModelOptions(
            name='child',
            options={'ordering': ['id'], 'verbose_name': 'Child', 'verbose_name_plural': 'Children'},
        ),
    ]
