# Generated by Django 2.1 on 2018-09-15 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ParticipantDB', '0009_auto_20180905_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='speakers',
            field=models.ManyToManyField(through='ParticipantDB.Speaks', to='ParticipantDB.Adult'),
        ),
        migrations.AlterField(
            model_name='speaks',
            name='language',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='languagespoken', to='ParticipantDB.Language'),
        ),
        migrations.AlterField(
            model_name='speaks',
            name='person',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='speaker', to='ParticipantDB.Adult'),
        ),
    ]
