# Generated by Django 2.1 on 2018-12-30 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ParticipantDB', '0010_auto_20181228_1614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessment',
            options={'ordering': ['assessment_name']},
        ),
        migrations.AlterModelOptions(
            name='assessment_run',
            options={'ordering': ['participantAdult', 'participantChild'], 'verbose_name': 'Assessment Run', 'verbose_name_plural': 'Assessment Runs'},
        ),
        migrations.AlterModelOptions(
            name='experiment',
            options={'ordering': ['experiment_name']},
        ),
        migrations.AlterModelOptions(
            name='experiment_section',
            options={'ordering': ['experiment_section_name'], 'verbose_name': 'Experiment Section', 'verbose_name_plural': 'Experiment Sections'},
        ),
        migrations.AlterModelOptions(
            name='experiment_section_field',
            options={'ordering': ['field_name'], 'verbose_name': 'Experiment Section Field', 'verbose_name_plural': 'Experiment Section Fields'},
        ),
        migrations.AlterModelOptions(
            name='experiment_section_run',
            options={'ordering': ['experiment_section', 'participantAdult', 'participantChild'], 'verbose_name': 'Experiment Section Run', 'verbose_name_plural': 'Experiment Section Runs'},
        ),
        migrations.AlterModelOptions(
            name='family',
            options={'ordering': ['id'], 'verbose_name': 'Family', 'verbose_name_plural': 'Families'},
        ),
        migrations.AddField(
            model_name='experiment_section_run',
            name='assessor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
