# Generated by Django 2.1 on 2019-02-18 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParticipantDB', '0011_auto_20190212_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speaks',
            name='nth_most_dominant',
        ),
        migrations.AddField(
            model_name='speaks',
            name='proficiency',
            field=models.CharField(choices=[('Native', 'Native'), ('Advanced', 'Advanced'), ('Intermediate', 'Intermediate'), ('Basic', 'Basic')], default='Basic', max_length=11),
        ),
    ]
