# Generated by Django 2.1 on 2019-02-18 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParticipantDB', '0012_auto_20190217_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicalexperience',
            name='nth_most_dominant',
        ),
        migrations.AddField(
            model_name='musicalexperience',
            name='proficiency',
            field=models.CharField(choices=[('Professional', 'Professional'), ('Advanced', 'Advanced'), ('Intermediate', 'Intermediate'), ('Basic', 'Basic')], default='Basic', max_length=11),
        ),
    ]
