# Generated by Django 2.1 on 2018-10-22 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ParticipantDB', '0013_auto_20181022_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment_Flex_Field',
            fields=[
                ('field_name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Field Name')),
                ('type', models.CharField(choices=[('num', 'Numeric'), ('passfail', 'Pass/Fail'), ('text', 'Text')], max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Assessment_Run_Field_Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.TextField(max_length=100)),
                ('assessment_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParticipantDB.Assessment_Flex_Field')),
            ],
        ),
        migrations.RenameField(
            model_name='assessment_run',
            old_name='adult_participant',
            new_name='participant',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='flex_1_max_value',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='flex_1_min_value',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='flex_1_name',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='flex_2_max_value',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='flex_2_min_value',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='flex_2_name',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='flex_3_max_value',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='flex_3_min_value',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='flex_3_name',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='flex_4_max_value',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='flex_4_min_value',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='flex_4_name',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='flex_5_max_value',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='flex_5_min_value',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='flex_5_name',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='flex_6_max_value',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='flex_6_min_value',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='flex_6_name',
        ),
        migrations.RemoveField(
            model_name='assessment_run',
            name='child_participant',
        ),
        migrations.RemoveField(
            model_name='assessment_run',
            name='flex_1_score',
        ),
        migrations.RemoveField(
            model_name='assessment_run',
            name='flex_2_score',
        ),
        migrations.RemoveField(
            model_name='assessment_run',
            name='flex_3_score',
        ),
        migrations.RemoveField(
            model_name='assessment_run',
            name='flex_4_score',
        ),
        migrations.RemoveField(
            model_name='assessment_run',
            name='flex_5_score',
        ),
        migrations.RemoveField(
            model_name='assessment_run',
            name='flex_6_score',
        ),
        migrations.AddField(
            model_name='assessment_run_field_score',
            name='assessment_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParticipantDB.Assessment_Run'),
        ),
        migrations.AddField(
            model_name='assessment_flex_field',
            name='field_of',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParticipantDB.Assessment'),
        ),
    ]
