# Generated by Django 2.1 on 2019-02-18 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParticipantDB', '0013_auto_20190217_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicalexperience',
            name='proficiency',
            field=models.CharField(choices=[('Professional', 'Professional'), ('Advanced', 'Advanced'), ('Intermediate', 'Intermediate'), ('Basic', 'Basic')], default='Basic', max_length=12),
        ),
    ]
