# Generated by Django 2.1 on 2019-02-18 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ParticipantDB', '0014_auto_20190217_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isparentin',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family', to='ParticipantDB.Family'),
        ),
    ]
