# Generated by Django 2.1 on 2018-10-25 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ParticipantDB', '0014_auto_20181022_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment_Field',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, verbose_name='Field Name')),
                ('type', models.CharField(choices=[('num', 'Numeric'), ('passfail', 'Pass/Fail'), ('text', 'Text')], max_length=8)),
                ('field_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParticipantDB.Assessment')),
            ],
        ),
        migrations.CreateModel(
            name='Experiment_Section_Field',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, verbose_name='Field Name')),
                ('type', models.CharField(choices=[('num', 'Numeric'), ('passfail', 'Pass/Fail'), ('text', 'Text')], max_length=8)),
                ('field_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParticipantDB.Experiment_Section')),
            ],
        ),
        migrations.RemoveField(
            model_name='assessment_flex_field',
            name='field_of',
        ),
        migrations.RemoveField(
            model_name='experiment_section_flex_field',
            name='field_of',
        ),
        migrations.AlterField(
            model_name='assessment_run_field_score',
            name='assessment_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParticipantDB.Assessment_Field'),
        ),
        migrations.AlterField(
            model_name='experiment_run_field_score',
            name='experiment_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParticipantDB.Experiment_Section_Field'),
        ),
        migrations.DeleteModel(
            name='Assessment_Flex_Field',
        ),
        migrations.DeleteModel(
            name='Experiment_Section_Flex_Field',
        ),
    ]
