# Generated by Django 2.1 on 2019-02-18 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ParticipantDB', '0015_auto_20190217_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ischildin',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ParticipantDB.Family'),
        ),
    ]
