# Generated by Django 2.1 on 2018-11-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParticipantDB', '0017_auto_20181110_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment_run_field_score',
            name='score',
            field=models.CharField(max_length=100),
        ),
    ]
