# Generated by Django 2.1.7 on 2019-03-05 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParticipantDB', '0017_auto_20190304_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment_section_field',
            name='type',
            field=models.CharField(choices=[('Numeric', 'Numeric'), ('Pass/Fail', 'Pass/Fail'), ('Text', 'Text')], max_length=9),
        ),
    ]
