# Generated by Django 2.1.7 on 2019-03-06 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParticipantDB', '0019_auto_20190305_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adult',
            name='languages',
            field=models.ManyToManyField(blank=True, through='ParticipantDB.Speaks', to='ParticipantDB.Language'),
        ),
    ]
