# Generated by Django 2.1.7 on 2019-03-06 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParticipantDB', '0020_auto_20190305_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adult',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='languages', through='ParticipantDB.Speaks', to='ParticipantDB.Language'),
        ),
    ]
