# Generated by Django 2.1 on 2018-11-15 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParticipantDB', '0021_auto_20181114_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment_section_field',
            name='type',
            field=models.CharField(choices=[('Numeric', 'Numeric'), ('Pass/Fail', 'Pass/Fail'), ('Text', 'Text')], max_length=8),
        ),
    ]
