# Generated by Django 2.1.7 on 2019-03-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParticipantDB', '0021_auto_20190305_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adult',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='speaks', through='ParticipantDB.Speaks', to='ParticipantDB.Language'),
        ),
    ]
