# Generated by Django 2.1.7 on 2019-03-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParticipantDB', '0022_auto_20190305_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaks',
            name='is_native',
            field=models.BooleanField(default=False, verbose_name='isNative'),
        ),
    ]
