# Generated by Django 2.1 on 2018-11-15 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParticipantDB', '0022_auto_20181114_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment_field',
            name='type',
            field=models.CharField(choices=[('Numeric', 'Numeric'), ('Pass/Fail', 'Pass/Fail'), ('Text', 'Text')], max_length=8),
        ),
    ]
