# Generated by Django 2.1.7 on 2019-03-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParticipantDB', '0023_auto_20190306_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaks',
            name='is_native',
            field=models.BooleanField(default=False),
        ),
    ]
