# Generated by Django 2.1 on 2018-11-15 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParticipantDB', '0025_auto_20181115_1029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lab',
            old_name='field',
            new_name='group',
        ),
    ]
