# Generated by Django 2.1 on 2018-11-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParticipantDB', '0026_auto_20181115_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='experiment_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
