# Generated by Django 2.2 on 2019-04-12 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParticipantDB', '0028_auto_20190411_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adult',
            name='pref_phone_time',
            field=models.CharField(blank=True, choices=[('WDM', 'Weekday Mornings'), ('WDA', 'Weekday Afternoons'), ('WDE', 'Weekday Evenings'), ('WEM', 'Weekend Mornings'), ('WEA', 'Weekend Afternoons'), ('WEE', 'Weekend Evenings'), ('ANY', 'Anytime'), ('DNC', 'Do Not Call')], max_length=3, null=True, verbose_name='Preferred Phone Time'),
        ),
    ]
