# Generated by Django 2.2 on 2019-04-12 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParticipantDB', '0029_auto_20190411_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment_run',
            name='notes',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
