# Generated by Django 2.1 on 2018-11-19 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParticipantDB', '0029_auto_20181119_0832'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experiment',
            options={},
        ),
    ]
