# Generated by Django 2.1 on 2018-11-19 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParticipantDB', '0030_auto_20181119_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiment_section',
            name='experiment',
        ),
        migrations.RemoveField(
            model_name='experiment_section_field',
            name='field_of',
        ),
        migrations.RemoveField(
            model_name='experiment_section_run',
            name='experiment_section',
        ),
        migrations.RemoveField(
            model_name='experiment_section_run',
            name='participantAdult',
        ),
        migrations.RemoveField(
            model_name='experiment_section_run',
            name='participantChild',
        ),
        migrations.RemoveField(
            model_name='experiment_section_run_field_score',
            name='experiment_field',
        ),
        migrations.RemoveField(
            model_name='experiment_section_run_field_score',
            name='experiment_run',
        ),
        migrations.DeleteModel(
            name='Experiment_Section',
        ),
        migrations.DeleteModel(
            name='Experiment_Section_Field',
        ),
        migrations.DeleteModel(
            name='Experiment_Section_Run',
        ),
        migrations.DeleteModel(
            name='Experiment_Section_Run_Field_Score',
        ),
    ]
