# Generated by Django 2.2 on 2019-04-12 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ParticipantDB', '0030_auto_20190411_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment_run',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_ran', to='ParticipantDB.Assessment'),
        ),
    ]
