# Generated by Django 2.1 on 2018-11-22 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParticipantDB', '0034_experiment_section_run_experiment_section_run_field_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiment_section_run_field_score',
            old_name='experiment_run',
            new_name='experiment_section_run',
        ),
    ]
