# Generated by Django 2.1 on 2018-11-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParticipantDB', '0036_auto_20181122_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment_section_run_field_score',
            name='score',
            field=models.CharField(max_length=100),
        ),
    ]
