# Generated by Django 2.1 on 2018-09-20 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParticipantDB', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musical_skill',
            options={'verbose_name': 'Musical Skill', 'verbose_name_plural': 'Musical Skills'},
        ),
    ]
