# Generated by Django 2.1 on 2018-09-20 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParticipantDB', '0002_auto_20180920_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musical_experience',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='musical_experience',
            name='person',
        ),
        migrations.RemoveField(
            model_name='adult',
            name='musical_background',
        ),
        migrations.DeleteModel(
            name='Musical_Experience',
        ),
        migrations.DeleteModel(
            name='Musical_Skill',
        ),
    ]
