# Generated by Django 2.1 on 2018-09-23 01:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ParticipantDB', '0010_auto_20180922_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicalexperience',
            name='age_learning_ended',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='musicalexperience',
            name='age_learning_started',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='musicalexperience',
            name='experience',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='instrument', to='ParticipantDB.MusicalSkill'),
        ),
        migrations.AlterField(
            model_name='musicalexperience',
            name='nth_most_dominant',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='speaks',
            name='age_learning_ended',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='speaks',
            name='age_learning_started',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='speaks',
            name='is_native',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='speaks',
            name='lang',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='languagespoken', to='ParticipantDB.Language'),
        ),
        migrations.AlterField(
            model_name='speaks',
            name='nth_most_dominant',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
