# Generated by Django 2.1 on 2018-10-08 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ParticipantDB', '0011_auto_20180922_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='isparentin',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family', to='ParticipantDB.Family'),
        ),
        migrations.AlterField(
            model_name='isparentin',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='ParticipantDB.Adult'),
        ),
    ]
