# Generated by Django 2.1 on 2018-10-22 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ParticipantDB', '0012_auto_20181008_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment_Run_Field_Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Experiment_Section_Flex_Field',
            fields=[
                ('field_name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Field Name')),
                ('type', models.CharField(choices=[('num', 'Numeric'), ('passfail', 'Pass/Fail'), ('text', 'Text')], max_length=8)),
            ],
        ),
        migrations.RenameField(
            model_name='experiment_section',
            old_name='section_of',
            new_name='part_of',
        ),
        migrations.RenameField(
            model_name='experiment_section_run',
            old_name='adult_participant',
            new_name='participant',
        ),
        migrations.RemoveField(
            model_name='experiment_section',
            name='flex_1_max_value',
        ),
        migrations.RemoveField(
            model_name='experiment_section',
            name='flex_1_min_value',
        ),
        migrations.RemoveField(
            model_name='experiment_section',
            name='flex_1_name',
        ),
        migrations.RemoveField(
            model_name='experiment_section',
            name='flex_2_max_value',
        ),
        migrations.RemoveField(
            model_name='experiment_section',
            name='flex_2_min_value',
        ),
        migrations.RemoveField(
            model_name='experiment_section',
            name='flex_2_name',
        ),
        migrations.RemoveField(
            model_name='experiment_section',
            name='flex_3_max_value',
        ),
        migrations.RemoveField(
            model_name='experiment_section',
            name='flex_3_min_value',
        ),
        migrations.RemoveField(
            model_name='experiment_section',
            name='flex_3_name',
        ),
        migrations.RemoveField(
            model_name='experiment_section',
            name='flex_4_max_value',
        ),
        migrations.RemoveField(
            model_name='experiment_section',
            name='flex_4_min_value',
        ),
        migrations.RemoveField(
            model_name='experiment_section',
            name='flex_4_name',
        ),
        migrations.RemoveField(
            model_name='experiment_section',
            name='flex_5_max_value',
        ),
        migrations.RemoveField(
            model_name='experiment_section',
            name='flex_5_min_value',
        ),
        migrations.RemoveField(
            model_name='experiment_section',
            name='flex_5_name',
        ),
        migrations.RemoveField(
            model_name='experiment_section',
            name='flex_6_max_value',
        ),
        migrations.RemoveField(
            model_name='experiment_section',
            name='flex_6_min_value',
        ),
        migrations.RemoveField(
            model_name='experiment_section',
            name='flex_6_name',
        ),
        migrations.RemoveField(
            model_name='experiment_section_run',
            name='child_participant',
        ),
        migrations.RemoveField(
            model_name='experiment_section_run',
            name='flex_1_score',
        ),
        migrations.RemoveField(
            model_name='experiment_section_run',
            name='flex_2_score',
        ),
        migrations.RemoveField(
            model_name='experiment_section_run',
            name='flex_3_score',
        ),
        migrations.RemoveField(
            model_name='experiment_section_run',
            name='flex_4_score',
        ),
        migrations.RemoveField(
            model_name='experiment_section_run',
            name='flex_5_score',
        ),
        migrations.RemoveField(
            model_name='experiment_section_run',
            name='flex_6_score',
        ),
        migrations.AddField(
            model_name='experiment_section_flex_field',
            name='field_of',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParticipantDB.Experiment_Section'),
        ),
        migrations.AddField(
            model_name='experiment_run_field_score',
            name='experiment_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParticipantDB.Experiment_Section_Flex_Field'),
        ),
        migrations.AddField(
            model_name='experiment_run_field_score',
            name='experiment_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParticipantDB.Experiment_Section_Run'),
        ),
    ]
