# Generated by Django 2.1 on 2018-11-10 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ParticipantDB', '0016_auto_20181025_0621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment_run',
            name='participant',
        ),
        migrations.AddField(
            model_name='assessment_run',
            name='participantAdult',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ParticipantDB.Adult'),
        ),
        migrations.AddField(
            model_name='assessment_run',
            name='participantChild',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ParticipantDB.Child'),
        ),
    ]
