# Generated by Django 2.1 on 2018-11-11 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParticipantDB', '0018_auto_20181110_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment_run',
            name='assessor',
            field=models.CharField(max_length=100),
        ),
    ]
