# Generated by Django 2.1 on 2018-11-11 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ParticipantDB', '0019_auto_20181110_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment_run',
            name='participantAdult',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ParticipantDB.Adult'),
        ),
        migrations.AlterField(
            model_name='assessment_run',
            name='participantChild',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ParticipantDB.Child'),
        ),
    ]
