# Generated by Django 2.1 on 2018-11-15 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ParticipantDB', '0020_auto_20181111_1253'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Experiment_Run_Field_Score',
            new_name='Experiment_Section_Run_Field_Score',
        ),
        migrations.RemoveField(
            model_name='experiment_section_run',
            name='participant',
        ),
        migrations.AddField(
            model_name='experiment_section_run',
            name='participantAdult',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ParticipantDB.Adult'),
        ),
        migrations.AddField(
            model_name='experiment_section_run',
            name='participantChild',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ParticipantDB.Child'),
        ),
    ]
