# Generated by Django 2.1 on 2018-11-19 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParticipantDB', '0027_auto_20181119_0822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experiment_section_field',
            options={'verbose_name': 'Experiment Section Field', 'verbose_name_plural': 'Experiment Section Fields'},
        ),
        migrations.RenameField(
            model_name='experiment_section',
            old_name='status',
            new_name='section_status',
        ),
    ]
