# Generated by Django 2.1 on 2018-11-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParticipantDB', '0035_auto_20181122_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment_section_run',
            name='assessor',
            field=models.CharField(max_length=100),
        ),
    ]
