# Generated by Django 2.1 on 2018-11-22 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParticipantDB', '0037_auto_20181122_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiment_section_run_field_score',
            old_name='experiment_field',
            new_name='experiment_section_field',
        ),
    ]
