# Generated by Django 2.1 on 2018-08-21 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0002_auto_20180821_1145'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Music',
            new_name='Musical_Experience',
        ),
    ]
