# Generated by Django 2.1 on 2018-08-21 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0003_auto_20180821_1147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'verbose_name_plural': 'Children'},
        ),
    ]
