# Generated by Django 2.1 on 2018-08-21 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0004_auto_20180821_1150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='langdev_experiment',
            options={'verbose_name': 'LangDev Experiment', 'verbose_name_plural': 'LangDev Experiments'},
        ),
        migrations.AlterModelOptions(
            name='langdev_experiment_section',
            options={'verbose_name': 'LangDev Experiment Section', 'verbose_name_plural': 'LangDev Experiment Sections'},
        ),
        migrations.AlterModelOptions(
            name='musical_experience',
            options={'verbose_name': 'Musical Experience', 'verbose_name_plural': 'Musical Experiences'},
        ),
        migrations.AlterModelOptions(
            name='phono_experiment',
            options={'verbose_name': 'Phono Experiment', 'verbose_name_plural': 'Phono Experiments'},
        ),
        migrations.AlterModelOptions(
            name='phono_experiment_section',
            options={'verbose_name': 'Phono Experiment Section', 'verbose_name_plural': 'Phono Experiment Sections'},
        ),
    ]
