# Generated by Django 2.1 on 2018-08-21 20:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0005_auto_20180821_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Speaks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_native', models.BooleanField()),
                ('nth_most_dominant', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('age_learning_started', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('age_learning_ended', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dbapp.Language')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dbapp.Adult')),
            ],
        ),
        migrations.AddField(
            model_name='adult',
            name='languages',
            field=models.ManyToManyField(through='dbapp.Speaks', to='dbapp.Language'),
        ),
    ]
