# Generated by Django 2.1 on 2018-08-21 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0006_auto_20180821_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsParentIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary_contact', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Is Parent In',
            },
        ),
        migrations.AlterModelOptions(
            name='family',
            options={'verbose_name_plural': 'Families'},
        ),
        migrations.AlterModelOptions(
            name='speaks',
            options={'verbose_name_plural': 'Speaks'},
        ),
        migrations.AddField(
            model_name='isparentin',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dbapp.Family'),
        ),
        migrations.AddField(
            model_name='isparentin',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dbapp.Adult'),
        ),
        migrations.AddField(
            model_name='adult',
            name='is_parent',
            field=models.ManyToManyField(through='dbapp.IsParentIn', to='dbapp.Family'),
        ),
    ]
