# Generated by Django 2.1 on 2018-08-21 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0007_auto_20180821_1346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='isparentin',
            options={'verbose_name_plural': 'Parents'},
        ),
    ]
