# Generated by Django 2.1 on 2018-08-21 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0008_auto_20180821_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adult',
            name='is_parent',
        ),
        migrations.AddField(
            model_name='adult',
            name='parent_in',
            field=models.ManyToManyField(blank=True, through='dbapp.IsParentIn', to='dbapp.Family'),
        ),
        migrations.AddField(
            model_name='child',
            name='family',
            field=models.ManyToManyField(to='dbapp.Family'),
        ),
    ]
