# Generated by Django 2.1 on 2018-08-21 21:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0009_auto_20180821_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsExperiencedIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nth_most_dominant', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('age_learning_started', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('age_learning_ended', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dbapp.Musical_Experience')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dbapp.Adult')),
            ],
            options={
                'verbose_name_plural': 'Musical Experience Relations',
            },
        ),
        migrations.CreateModel(
            name='IsExposedTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage_exposure', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dbapp.Child')),
            ],
            options={
                'verbose_name_plural': 'Is Exposed To',
            },
        ),
        migrations.RemoveField(
            model_name='language',
            name='id',
        ),
        migrations.AlterField(
            model_name='language',
            name='language_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='isexposedto',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dbapp.Language'),
        ),
        migrations.AddField(
            model_name='adult',
            name='musical_experiences',
            field=models.ManyToManyField(through='dbapp.IsExperiencedIn', to='dbapp.Musical_Experience'),
        ),
        migrations.AddField(
            model_name='child',
            name='exposed_to',
            field=models.ManyToManyField(through='dbapp.IsExposedTo', to='dbapp.Language'),
        ),
    ]
