# Generated by Django 2.1 on 2018-08-21 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0010_auto_20180821_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment_name', models.CharField(max_length=100)),
                ('lab', models.CharField(choices=[('ld', 'LangDev'), ('ph', 'Phono')], max_length=2)),
                ('status', models.CharField(choices=[('prep', 'In Prep'), ('recruiting', 'Actively Recruiting'), ('inactive', 'Inactive')], max_length=10)),
            ],
            options={
                'verbose_name': 'Experiment',
                'verbose_name_plural': 'Experiments',
            },
        ),
        migrations.CreateModel(
            name='Experiment_Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment_section_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('prep', 'In Prep'), ('recruiting', 'Actively Recruiting'), ('inactive', 'Inactive')], max_length=10)),
                ('section_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbapp.Language')),
            ],
            options={
                'verbose_name': 'Experiment Section',
                'verbose_name_plural': 'Experiment Sections',
            },
        ),
        migrations.CreateModel(
            name='Participated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notes', models.TextField(max_length=1000)),
                ('assessor', models.TextField(max_length=100)),
            ],
            options={
                'verbose_name': 'Participation',
                'verbose_name_plural': 'Participations',
            },
        ),
        migrations.DeleteModel(
            name='Langdev_Experiment',
        ),
        migrations.DeleteModel(
            name='Langdev_Experiment_Section',
        ),
        migrations.DeleteModel(
            name='Phono_Experiment',
        ),
        migrations.DeleteModel(
            name='Phono_Experiment_Section',
        ),
        migrations.AddField(
            model_name='child',
            name='surname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='adult',
            name='surname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='participated',
            name='adult_participant',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='dbapp.Adult'),
        ),
        migrations.AddField(
            model_name='participated',
            name='child_participant',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='dbapp.Child'),
        ),
        migrations.AddField(
            model_name='participated',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dbapp.Experiment_Section'),
        ),
        migrations.AddField(
            model_name='adult',
            name='participations',
            field=models.ManyToManyField(blank=True, through='dbapp.Participated', to='dbapp.Experiment_Section'),
        ),
        migrations.AddField(
            model_name='child',
            name='participations',
            field=models.ManyToManyField(blank=True, through='dbapp.Participated', to='dbapp.Experiment_Section'),
        ),
    ]
